# Generated by Django 2.2.5 on 2019-12-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='answers',
        ),
        migrations.AddField(
            model_name='answers',
            name='answers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Comment', verbose_name='Ответ'),
        ),
    ]
