# Generated by Django 2.2.5 on 2019-12-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191226_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answers',
            new_name='comment',
        ),
    ]
