# Generated by Django 2.2.5 on 2019-12-27 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191226_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Comment', verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
