# Generated by Django 2.2.16 on 2020-12-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191227_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Имя')),
                ('text', models.TextField(max_length=200, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Обратная связь',
            },
        ),
    ]
